@startuml

class "Nøglepartnere" as NP{
}
class "Nøgleaktiviteter" as NA{
}
class "Nøgleressourcer" as NR{
}
class "Værditilbud" as Væ {
}
class "Kunderelationer" as KR{
}
class "Kanaler" as Ka{
}
class "Kundesegmenter" as KS{
}
class "Omkostningsstruktur" as OS{
}
class "Indtægtsstrømme" as IS{
}

hide methods
hide circle

@enduml